spring:
  profiles:
    active: local

---
spring.config.activate.on-profile: local

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

katfun:
  week04:
    host: https://katfun.whatever.com
